# Generated by Django 4.0.7 on 2026-02-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhistleCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='사건명')),
                ('category', models.CharField(choices=[('인권', '인권'), ('노동', '노동'), ('환경', '환경'), ('건강', '건강'), ('안전', '안전'), ('소비자이익', '소비자이익'), ('공정한 경쟁', '공정한 경쟁'), ('교육', '교육'), ('민주주의/행정 공정성', '민주주의/행정 공정성'), ('기타/침해영역', '기타/침해영역')], default='', max_length=50, verbose_name='분류')),
                ('whistleblower', models.CharField(default='', max_length=100, verbose_name='제보자')),
                ('organization', models.CharField(default='', max_length=150, verbose_name='대상기관/기업')),
                ('case_year', models.CharField(default='', max_length=4, verbose_name='사건년도')),
                ('summary', models.TextField(blank=True, verbose_name='개요')),
                ('content', models.TextField(blank=True, verbose_name='상세내용')),
                ('outcome', models.TextField(blank=True, verbose_name='결과/판결')),
                ('significance', models.TextField(blank=True, verbose_name='의의')),
                ('memo', models.TextField(blank=True, verbose_name='참고')),
                ('hide', models.BooleanField(default=False, verbose_name='비공개')),
            ],
            options={
                'verbose_name': '공익제보 사건',
                'verbose_name_plural': '공익제보 사건',
            },
        ),
        migrations.CreateModel(
            name='WhistleTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField(null=True, verbose_name='날짜')),
                ('title', models.CharField(default='', max_length=150, verbose_name='제목')),
                ('contents', models.TextField(blank=True, verbose_name='내용')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whistle.whistlecase')),
            ],
            options={
                'verbose_name': '타임라인',
                'verbose_name_plural': '타임라인',
            },
        ),
        migrations.CreateModel(
            name='WhistleArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=50, verbose_name='출처')),
                ('title', models.CharField(default='', max_length=150, verbose_name='제목')),
                ('link', models.CharField(default='', max_length=255, verbose_name='URL')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whistle.whistlecase')),
            ],
            options={
                'verbose_name': '관련기사',
                'verbose_name_plural': '관련기사',
            },
        ),
    ]
