# Generated by Django 4.0.7 on 2026-02-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whistlecase',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='whistlecase',
            name='significance',
        ),
        migrations.RemoveField(
            model_name='whistlecase',
            name='summary',
        ),
        migrations.AddField(
            model_name='whistlecase',
            name='awards',
            field=models.TextField(blank=True, verbose_name='수상이력'),
        ),
        migrations.AddField(
            model_name='whistlecase',
            name='hidden_disadvantage',
            field=models.TextField(blank=True, verbose_name='비공개_불이익상세'),
        ),
        migrations.AddField(
            model_name='whistlecase',
            name='hidden_violation',
            field=models.TextField(blank=True, verbose_name='비공개_위반행위'),
        ),
        migrations.AddField(
            model_name='whistlecase',
            name='media_coverage',
            field=models.TextField(blank=True, verbose_name='미디어_언론보도'),
        ),
        migrations.AddField(
            model_name='whistlecase',
            name='media_detail',
            field=models.TextField(blank=True, verbose_name='언론보도 내역'),
        ),
        migrations.AddField(
            model_name='whistlecase',
            name='media_photo',
            field=models.TextField(blank=True, verbose_name='미디어_사진'),
        ),
        migrations.AddField(
            model_name='whistlecase',
            name='quote',
            field=models.TextField(blank=True, verbose_name='제보자 한마디'),
        ),
        migrations.AddField(
            model_name='whistlecase',
            name='situation',
            field=models.TextField(blank=True, verbose_name='제보자 상황'),
        ),
        migrations.AddField(
            model_name='whistlecase',
            name='support',
            field=models.TextField(blank=True, verbose_name='참여연대 지원'),
        ),
        migrations.AddField(
            model_name='whistlecase',
            name='tags',
            field=models.CharField(default='', max_length=255, verbose_name='주요태그'),
        ),
        migrations.AlterField(
            model_name='whistlecase',
            name='case_year',
            field=models.CharField(default='', max_length=4, verbose_name='제보년도'),
        ),
        migrations.AlterField(
            model_name='whistlecase',
            name='category',
            field=models.CharField(choices=[('인권', '인권'), ('노동', '노동'), ('환경', '환경'), ('건강', '건강'), ('안전', '안전'), ('소비자이익', '소비자이익'), ('공정한 경쟁', '공정한 경쟁'), ('교육', '교육'), ('민주주의/행정공정성', '민주주의/행정공정성'), ('기타/침해영역', '기타/침해영역')], default='', max_length=50, verbose_name='공익침해영역'),
        ),
        migrations.AlterField(
            model_name='whistlecase',
            name='content',
            field=models.TextField(blank=True, verbose_name='제보내용'),
        ),
        migrations.AlterField(
            model_name='whistlecase',
            name='organization',
            field=models.CharField(default='', max_length=150, verbose_name='제보대상기관'),
        ),
        migrations.AlterField(
            model_name='whistlecase',
            name='whistleblower',
            field=models.CharField(default='', max_length=100, verbose_name='제보자 성명'),
        ),
    ]
