# Generated by Django 4.0.7 on 2026-02-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistle', '0002_remove_whistlecase_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistlecase',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='whistle/thumbnails/', verbose_name='썸네일'),
        ),
    ]
