# Generated by Django 4.0.7 on 2026-02-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistle', '0003_whistlecase_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistlearticle',
            name='rdate',
            field=models.DateField(blank=True, null=True, verbose_name='날짜'),
        ),
    ]
