# Generated by Django 4.0.7 on 2026-02-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whistle', '0004_whistlearticle_rdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhistleCheer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='작성자명')),
                ('content', models.TextField(verbose_name='응원 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheers', to='whistle.whistlecase')),
            ],
            options={
                'verbose_name': '응원글',
                'verbose_name_plural': '응원글',
                'ordering': ['-created_at'],
            },
        ),
    ]
