# Generated by Django 4.0.7 on 2026-03-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistle', '0005_whistlecheer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistlecase',
            name='category',
            field=models.CharField(choices=[('인권·노동', '인권·노동'), ('환경·건강·안전', '환경·건강·안전'), ('소비자이익·공정경쟁', '소비자이익·공정경쟁'), ('학사·연구부정', '학사·연구부정'), ('민주주의·권한남용', '민주주의·권한남용'), ('공공재정', '공공재정')], default='', max_length=50, verbose_name='공익침해영역'),
        ),
    ]
