# Generated by Django 4.0.7 on 2026-03-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistle', '0006_alter_whistlecase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whistlecase',
            name='category',
            field=models.CharField(choices=[('인권·노동', '인권·노동'), ('환경·건강·안전', '환경·건강·안전'), ('소비자이익·공정경쟁', '소비자이익·공정경쟁'), ('학사·연구부정', '학사·연구부정'), ('민주주의·권한남용', '민주주의·권한남용'), ('공공재정', '공공재정')], default='', max_length=50, verbose_name='공익침해분야'),
        ),
        migrations.AlterField(
            model_name='whistlecase',
            name='organization',
            field=models.CharField(choices=[('행정·공공기관', '행정·공공기관'), ('군·정보기관', '군·정보기관'), ('민간기업', '민간기업'), ('교육기관', '교육기관'), ('비영리단체', '비영리단체'), ('수사·조사기관', '수사·조사기관'), ('기타', '기타')], default='', max_length=50, verbose_name='신고대상'),
        ),
    ]
