# Generated by Django 4.0.7 on 2026-03-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistle', '0007_alter_whistlecase_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistlecase',
            name='prize',
            field=models.BooleanField(default=False, verbose_name='참여연대 공익제보자상 수상'),
        ),
        migrations.AlterField(
            model_name='whistlecase',
            name='category',
            field=models.CharField(choices=[('공공재정', '공공재정'), ('민주주의·권한남용', '민주주의·권한남용'), ('소비자이익·공정경쟁', '소비자이익·공정경쟁'), ('인권·노동', '인권·노동'), ('학사·연구부정', '학사·연구부정'), ('환경·건강·안전', '환경·건강·안전')], default='', max_length=50, verbose_name='공익침해분야'),
        ),
        migrations.AlterField(
            model_name='whistlecase',
            name='hidden_disadvantage',
            field=models.TextField(blank=True, verbose_name='불이익상세'),
        ),
        migrations.AlterField(
            model_name='whistlecase',
            name='hidden_violation',
            field=models.TextField(blank=True, verbose_name='위반행위'),
        ),
        migrations.AlterField(
            model_name='whistlecase',
            name='organization',
            field=models.CharField(choices=[('교육기관', '교육기관'), ('군·정보기관', '군·정보기관'), ('민간기업', '민간기업'), ('비영리단체', '비영리단체'), ('수사·조사기관', '수사·조사기관'), ('행정·공공기관', '행정·공공기관'), ('기타', '기타')], default='', max_length=50, verbose_name='신고대상'),
        ),
    ]
