# Generated by Django 4.0.7 on 2026-05-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistle', '0008_whistlecase_prize_alter_whistlecase_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistlecase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일'),
        ),
        migrations.AddField(
            model_name='whistlecase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='whistlecase',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='주요태그'),
        ),
    ]
