# Generated by Django 4.0.7 on 2026-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistle', '0009_whistlecase_created_at_whistlecase_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistlecase',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='메인 노출'),
        ),
    ]
